# frozen_string_literal: true

source "https://rubygems.org"

group :test do
  gem 'rspec'
  gem 'simplecov', require: false
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'csv'
end

# gem "rails"
